/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-Stream_Blocks
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_STREAM_BLOCKS_API_H
#define INCLUDED_STREAM_BLOCKS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_Stream_Blocks_EXPORTS
#define STREAM_BLOCKS_API __GR_ATTR_EXPORT
#else
#define STREAM_BLOCKS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_STREAM_BLOCKS_API_H */
